/* GENERATED by scripts/outlook/export_package.py — do not edit.
 *
 * The model outlook's parameter package (model-outlook.js reads it):
 * EWMA variance with standardized Student-t innovations for the next
 * completed hour of BTC-USD on Coinbase Exchange, fitted on the 730 days
 * before the cutoff and evaluated out of sample under the preregistration
 * docs/internal/research/model-outlook-prereg.md. Data, not code. */
const OUTLOOK_MODEL = {
  "schema": "pricetab.outlook.model/1",
  "id": "ewma-t-2026-10-01",
  "instrument": "BTC-USD",
  "venue": "Coinbase Exchange (spot)",
  "pair": "BTC-USD",
  "bar": "1h, UTC hour starting at its time; price = the bar's close",
  "returns": "decimal log returns, ln(S_t / S_t-1)",
  "horizon": "1 bar (1h), terminal",
  "method": "ewma",
  "dist": "t",
  "params": {
    "lambda": 0.9144052336,
    "nu": 3.96636792
  },
  "fit": {
    "window": [
      "2024-09-30T23:00:00Z",
      "2026-10-01T00:00:00Z"
    ],
    "bars": 17520,
    "loglik_percent_units": -8219.9514,
    "converged": true
  },
  "cutoff": "2026-10-01T00:00:00Z",
  "checkpoint": {
    "time": 1790809200000,
    "v": 2.121980727517618e-05,
    "note": "variance of the return of the bar after `time`, decimal units"
  },
  "validity": {
    "minBars": 500,
    "maxAgeMs": 7200000,
    "maxGapBars": 6,
    "gapRecoveryBars": 48
  },
  "data": {
    "source": "Coinbase Exchange public REST, /products/{product}/candles",
    "first": "2016-01-01T00:00:00Z",
    "last": "2026-09-30T23:00:00Z",
    "rows": 94169,
    "missing_hours": 55,
    "csv_sha256": "187af15e7a8c1157501b97138353b56dd5fb5b2f26cfa7a8561c3f88f03d42ff"
  },
  "evaluation": {
    "status": "passed",
    "selection": "lowest interval score among ['ewma_t']: ewma_t",
    "period": [
      "2025-01-01",
      "2026-10-01"
    ],
    "n": 15302,
    "nominal": 0.8,
    "coverage80": 0.7782,
    "width80_pct": 0.8946,
    "interval_score": 1.59393,
    "baseline": "rolling 24h variance, Normal",
    "baseline_interval_score": 1.62994,
    "dm_t_vs_baseline": -8.189,
    "reliability": [
      [
        0,
        0.01,
        17822,
        0.00426,
        0.01044
      ],
      [
        0.01,
        0.025,
        11656,
        0.01653,
        0.02574
      ],
      [
        0.025,
        0.05,
        10325,
        0.03642,
        0.04571
      ],
      [
        0.05,
        0.1,
        11174,
        0.07199,
        0.0767
      ],
      [
        0.1,
        0.2,
        8133,
        0.13912,
        0.12689
      ],
      [
        0.2,
        0.35,
        2095,
        0.24607,
        0.221
      ],
      [
        0.35,
        1,
        3,
        0.35253,
        0.33333
      ]
    ]
  }
};
